### ISSUE TITLE
More detailed instructions to get started

### ISSUE THREAD

**Issue by cachan3543** [neopostmodern/cgtrader-downloader#2]
you did not give instructions on how to install and how to run it
I have the ZIP unpacked in the download, and have Firefox 
Where do I install that for firefox and how do I get it to work?

**Comment by neopostmodern** [comment]
Have you read the README? It outlines installation and usage. If there are specific uncertainties with the instructions, let me know.
(To clarify, a pre-installed Firefox is a requirement, but the script does not run *inside* Firefox, it launches its own instance of Firefox once you execute it.)

**Comment by cachan3543** [comment]
oh, I am uncertain of ALL of the instructions, literally, I do apologize
I need a step-by-step guide on how to do this

**Comment by neopostmodern** [comment]
I'm happy to include more detailed instructions in the README if someone writes them down, for me this is currently beyond capacities. I'll reopen the issue though if someone wants to pick it up.

**Comment by cachan3543** [comment]
true enough, I am not familiar with how it works

**Comment by ljavuras** [comment]
`pip3 -r requirements.txt` resulted in an error `no such option: -r`, did you mean `pip3 install -r requirements.txt`?

**Comment by neopostmodern** [comment]
Ugh, good catch @ljavuras – will update README!

**Comment by CarlesRincon** [comment]
Greetings, when I try to download by running the code,

python3 main.py "https://cgtrader.com/CGTRADER_MODEL_PAGE_PATH"

This is what appears.

Python not found; run without arguments to install from the Microsoft Store or disable this shortcut from Settings > Apps > Advanced app settings > App launch aliases.

I don't know what's wrong. I installed it, as the readme says, and everything went fine, but when I got to that part, it doesn't work. I'd appreciate it if you could clarify what I should do. Thanks in advance for the tool. I hope it works.

**Comment by neopostmodern** [comment]
Instructions on how to install Python are out of scope for this repository. There's plenty of information online you can find.

**Comment by CarlesRincon** [comment]
Greetings, I've already solved the Python installation, and the code that worked for me was...

python main.py "https://cgtrader.com/CGTRADER_MODEL_PAGE_PATH"

The problem is that when I run it, I get this error and it doesn't download.

Downloading models from 1 URL.
Ensuring logged in...
No accounts available - creating a new one.
Creating account...
Registered new email address LHC8U6QF@ulm-dsl.de.
Traceback (most recent call last): 
File "C:\Users\Carles\AppData\Local\Programs\Python\Python313\main.py", line 142, in <module> 
scrape(urls) 
~~~~~~^^^^^^ 
File "C:\Users\Carles\AppData\Local\Programs\Python\Python313\main.py", line 39, in scrape 
account_manager.ensure_logged_in() 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ 
File "C:\Users\Carles\AppData\Local\Programs\Python\Python313\cgtrader_accounts.py", line 101, in ensure_logged_in 
self._create_credentials() 
~~~~~~~~~~~~~~~~~~~~~~~~~^^ 
File "C:\Users\Carles\AppData\Local\Programs\Python\Python313\cgtrader_accounts.py", line 139, in _create_credentials 
).click() 
~~~~~^^ 
File "C:\Users\Carles\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click 
self._execute(Command.CLICK_ELEMENT) 
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^ 
File "C:\Users\Carles\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute 
return self._parent.execute(command, params) 
~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^ 
File "C:\Users\Carles\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute 
self.error_handler.check_response(response) 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^ 
File "C:\Users\Carles\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response 
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <li> is not clickable at point (1168,92) because another element <a id="697ad07b7d03b7edf9b980ae048c288e" class="js-shopping-cart-icon" href="/cg/checkout/cart"> obscures Item
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
ElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:351:5
webdriverClickElement@chrome://remote/content/marionette/in teraction.sys.mjs:177:11
interaction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:354:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:230:31

Could someone help me?

**Comment by neopostmodern** [comment]
That seems like an actual bug. I don't have time to look into at the moment, but can you please open a separate issue with a specific URL where the error occurs?
